### ISSUE TITLE
Pagination - first page number always links to page 1

### ISSUE THREAD

**Issue by SOHOIT** [wp-e-commerce/WP-e-Commerce#2031]
- WordPress: v. 4.3.1
- WP eCommerce: v. 3.11.0
- Theme: Twenty Fifteen
- No other plugins active

Using pagination in product categories the first page number displayed always points to the root of the category. When the first page displayed in the pagination links is not page one the link should be to the appropriate page number. (i.e. page 2 should link to the page 2)

For an example of the issue see  http://www.saxpress.com/store/saxophone-quartet/page/6/

The link for page '2' is to /store/saxophone-quartet/, it should be to /store/saxophone-quartet/page/2/

**Comment by JustinSainton** [comment]
I believe this was fixed in 3.11.1

**Comment by SOHOIT** [comment]
Justin,

The issue is still occurring both in 3.11.1 and 3.11.2

**Comment by misulicus** [comment]
Hey @SOHOIT 
Can you apply this code change and give it another test please:

Open the file `wp-e-commerce/wpsc-components/theme-engine-v1/helpers/template-tags.php`
head to line 406

You should have this: `if($count == 1)`
Replace with: `if($i== 1)`

Give it a test and let us know

**Comment by SOHOIT** [comment]
@misulicus This resolves the issue on product category pagination.

I can't test on product tags pagination due to issue #2021
